### ISSUE TITLE
Issue with pluralisation '=2'

### ISSUE THREAD

**Issue by mikusdCN** [rocwong/gulp-po2json-angular-translate#2]
Hi,
Is there any reason for the hard coded '=2' in converted jsons?
It's causing me issues with pluralised texts.
For default offset 1
Let's say I have a simple label:

```
msgid "match"
msgid_plural "match"
msgstr[0] "%d match"
msgstr[1] "%d matches"
```

this is converted into 
`"{PLURALIZE, plural, offset:1 =2{# match} other{# matches}}"`

For value 1, the translated text is '0 matches'.

When I change offset to 0, It's wrong again.
For value 1, the translation is '1 matches'
For value 2, the translation is '2 match'

This is caused by hard coded '=2' in conversion itself.

Is this intentional?

**Comment by rocwong** [comment]
Yes, it is intentional, But i am so sorry i don't know the reason too.
The core code is based on [grunt-po2json-angular-translate v0.0.3](https://github.com/angular-translate/grunt-po2json-angular-translate#pluralization).

**Comment by mikusdCN** [comment]
I wonder If Im just using it incorrectly or Its actual issue.
Do you know, If there is some recommendation about displaying proper translation?
Thank you

**Comment by rocwong** [comment]
I think it's an actual issue after i read the 'messageformat' documentation.
I will fix it tomorrow.

**Comment by rocwong** [comment]
You can update and try it now.
